# Generated by Django 4.2.2 on 2024-10-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_appointment_options_appointment_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services_image'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
