# Generated by Django 4.2.2 on 2024-10-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_appointment_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
    ]
