# Generated by Django 4.2.2 on 2024-10-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_appointment_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-is_paid'], 'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت ها'},
        ),
    ]
